(define (problem problem_d1_r0_l25_p25_c25_g25)
  (:domain emergency-services)
  (:objects
    drone1 - drone
    depot - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    loc10 - location
    loc11 - location
    loc12 - location
    loc13 - location
    loc14 - location
    loc15 - location
    loc16 - location
    loc17 - location
    loc18 - location
    loc19 - location
    loc20 - location
    loc21 - location
    loc22 - location
    loc23 - location
    loc24 - location
    loc25 - location
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    person10 - person
    person11 - person
    person12 - person
    person13 - person
    person14 - person
    person15 - person
    person16 - person
    person17 - person
    person18 - person
    person19 - person
    person20 - person
    person21 - person
    person22 - person
    person23 - person
    person24 - person
    person25 - person
    crate1 - crate
    crate2 - crate
    crate3 - crate
    crate4 - crate
    crate5 - crate
    crate6 - crate
    crate7 - crate
    crate8 - crate
    crate9 - crate
    crate10 - crate
    crate11 - crate
    crate12 - crate
    crate13 - crate
    crate14 - crate
    crate15 - crate
    crate16 - crate
    crate17 - crate
    crate18 - crate
    crate19 - crate
    crate20 - crate
    crate21 - crate
    crate22 - crate
    crate23 - crate
    crate24 - crate
    crate25 - crate
    food - content
    medicine - content
    left - arm
    right - arm
  )
  (:init
    (at-drone drone1 depot)
    (hand-empty drone1 left)
    (hand-empty drone1 right)
    (at-crate crate1 depot)
    (at-crate crate2 depot)
    (at-crate crate3 depot)
    (at-crate crate4 depot)
    (at-crate crate5 depot)
    (at-crate crate6 depot)
    (at-crate crate7 depot)
    (at-crate crate8 depot)
    (at-crate crate9 depot)
    (at-crate crate10 depot)
    (at-crate crate11 depot)
    (at-crate crate12 depot)
    (at-crate crate13 depot)
    (at-crate crate14 depot)
    (at-crate crate15 depot)
    (at-crate crate16 depot)
    (at-crate crate17 depot)
    (at-crate crate18 depot)
    (at-crate crate19 depot)
    (at-crate crate20 depot)
    (at-crate crate21 depot)
    (at-crate crate22 depot)
    (at-crate crate23 depot)
    (at-crate crate24 depot)
    (at-crate crate25 depot)
    (at-person person1 loc12)
    (at-person person2 loc4)
    (at-person person3 loc6)
    (at-person person4 loc1)
    (at-person person5 loc13)
    (at-person person6 loc16)
    (at-person person7 loc15)
    (at-person person8 loc12)
    (at-person person9 loc6)
    (at-person person10 loc18)
    (at-person person11 loc12)
    (at-person person12 loc18)
    (at-person person13 loc8)
    (at-person person14 loc15)
    (at-person person15 loc21)
    (at-person person16 loc18)
    (at-person person17 loc15)
    (at-person person18 loc7)
    (at-person person19 loc11)
    (at-person person20 loc6)
    (at-person person21 loc18)
    (at-person person22 loc16)
    (at-person person23 loc12)
    (at-person person24 loc3)
    (at-person person25 loc21)
    (crate-content crate1 food)
    (crate-content crate2 food)
    (crate-content crate3 food)
    (crate-content crate4 food)
    (crate-content crate5 food)
    (crate-content crate6 food)
    (crate-content crate7 food)
    (crate-content crate8 food)
    (crate-content crate9 food)
    (crate-content crate10 food)
    (crate-content crate11 food)
    (crate-content crate12 food)
    (crate-content crate13 food)
    (crate-content crate14 food)
    (crate-content crate15 food)
    (crate-content crate16 food)
    (crate-content crate17 food)
    (crate-content crate18 food)
    (crate-content crate19 food)
    (crate-content crate20 food)
    (crate-content crate21 food)
    (crate-content crate22 food)
    (crate-content crate23 medicine)
    (crate-content crate24 medicine)
    (crate-content crate25 medicine)
  )
  (:goal (and
    (has-content person1 food)
    (has-content person2 food)
    (has-content person3 food)
    (has-content person3 medicine)
    (has-content person4 food)
    (has-content person5 food)
    (has-content person5 medicine)
    (has-content person6 food)
    (has-content person8 food)
    (has-content person9 food)
    (has-content person10 food)
    (has-content person12 food)
    (has-content person13 food)
    (has-content person14 food)
    (has-content person15 food)
    (has-content person15 medicine)
    (has-content person16 food)
    (has-content person18 food)
    (has-content person19 food)
    (has-content person20 food)
    (has-content person21 food)
    (has-content person22 food)
    (has-content person23 food)
    (has-content person24 food)
    (has-content person25 food)
  ))
)
