(define (problem problem_d1_r0_l45_p45_c45_g45)
  (:domain emergency-services)
  (:objects
    drone1 - drone
    depot - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    loc10 - location
    loc11 - location
    loc12 - location
    loc13 - location
    loc14 - location
    loc15 - location
    loc16 - location
    loc17 - location
    loc18 - location
    loc19 - location
    loc20 - location
    loc21 - location
    loc22 - location
    loc23 - location
    loc24 - location
    loc25 - location
    loc26 - location
    loc27 - location
    loc28 - location
    loc29 - location
    loc30 - location
    loc31 - location
    loc32 - location
    loc33 - location
    loc34 - location
    loc35 - location
    loc36 - location
    loc37 - location
    loc38 - location
    loc39 - location
    loc40 - location
    loc41 - location
    loc42 - location
    loc43 - location
    loc44 - location
    loc45 - location
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    person10 - person
    person11 - person
    person12 - person
    person13 - person
    person14 - person
    person15 - person
    person16 - person
    person17 - person
    person18 - person
    person19 - person
    person20 - person
    person21 - person
    person22 - person
    person23 - person
    person24 - person
    person25 - person
    person26 - person
    person27 - person
    person28 - person
    person29 - person
    person30 - person
    person31 - person
    person32 - person
    person33 - person
    person34 - person
    person35 - person
    person36 - person
    person37 - person
    person38 - person
    person39 - person
    person40 - person
    person41 - person
    person42 - person
    person43 - person
    person44 - person
    person45 - person
    crate1 - crate
    crate2 - crate
    crate3 - crate
    crate4 - crate
    crate5 - crate
    crate6 - crate
    crate7 - crate
    crate8 - crate
    crate9 - crate
    crate10 - crate
    crate11 - crate
    crate12 - crate
    crate13 - crate
    crate14 - crate
    crate15 - crate
    crate16 - crate
    crate17 - crate
    crate18 - crate
    crate19 - crate
    crate20 - crate
    crate21 - crate
    crate22 - crate
    crate23 - crate
    crate24 - crate
    crate25 - crate
    crate26 - crate
    crate27 - crate
    crate28 - crate
    crate29 - crate
    crate30 - crate
    crate31 - crate
    crate32 - crate
    crate33 - crate
    crate34 - crate
    crate35 - crate
    crate36 - crate
    crate37 - crate
    crate38 - crate
    crate39 - crate
    crate40 - crate
    crate41 - crate
    crate42 - crate
    crate43 - crate
    crate44 - crate
    crate45 - crate
    food - content
    medicine - content
    left - arm
    right - arm
  )
  (:init
    (at-drone drone1 depot)
    (hand-empty drone1 left)
    (hand-empty drone1 right)
    (at-crate crate1 depot)
    (at-crate crate2 depot)
    (at-crate crate3 depot)
    (at-crate crate4 depot)
    (at-crate crate5 depot)
    (at-crate crate6 depot)
    (at-crate crate7 depot)
    (at-crate crate8 depot)
    (at-crate crate9 depot)
    (at-crate crate10 depot)
    (at-crate crate11 depot)
    (at-crate crate12 depot)
    (at-crate crate13 depot)
    (at-crate crate14 depot)
    (at-crate crate15 depot)
    (at-crate crate16 depot)
    (at-crate crate17 depot)
    (at-crate crate18 depot)
    (at-crate crate19 depot)
    (at-crate crate20 depot)
    (at-crate crate21 depot)
    (at-crate crate22 depot)
    (at-crate crate23 depot)
    (at-crate crate24 depot)
    (at-crate crate25 depot)
    (at-crate crate26 depot)
    (at-crate crate27 depot)
    (at-crate crate28 depot)
    (at-crate crate29 depot)
    (at-crate crate30 depot)
    (at-crate crate31 depot)
    (at-crate crate32 depot)
    (at-crate crate33 depot)
    (at-crate crate34 depot)
    (at-crate crate35 depot)
    (at-crate crate36 depot)
    (at-crate crate37 depot)
    (at-crate crate38 depot)
    (at-crate crate39 depot)
    (at-crate crate40 depot)
    (at-crate crate41 depot)
    (at-crate crate42 depot)
    (at-crate crate43 depot)
    (at-crate crate44 depot)
    (at-crate crate45 depot)
    (at-person person1 loc3)
    (at-person person2 loc29)
    (at-person person3 loc22)
    (at-person person4 loc39)
    (at-person person5 loc34)
    (at-person person6 loc7)
    (at-person person7 loc43)
    (at-person person8 loc39)
    (at-person person9 loc22)
    (at-person person10 loc41)
    (at-person person11 loc35)
    (at-person person12 loc32)
    (at-person person13 loc28)
    (at-person person14 loc9)
    (at-person person15 loc11)
    (at-person person16 loc12)
    (at-person person17 loc29)
    (at-person person18 loc43)
    (at-person person19 loc34)
    (at-person person20 loc36)
    (at-person person21 loc15)
    (at-person person22 loc41)
    (at-person person23 loc44)
    (at-person person24 loc19)
    (at-person person25 loc6)
    (at-person person26 loc42)
    (at-person person27 loc19)
    (at-person person28 loc9)
    (at-person person29 loc37)
    (at-person person30 loc42)
    (at-person person31 loc34)
    (at-person person32 loc36)
    (at-person person33 loc2)
    (at-person person34 loc16)
    (at-person person35 loc4)
    (at-person person36 loc27)
    (at-person person37 loc38)
    (at-person person38 loc36)
    (at-person person39 loc39)
    (at-person person40 loc26)
    (at-person person41 loc40)
    (at-person person42 loc3)
    (at-person person43 loc33)
    (at-person person44 loc9)
    (at-person person45 loc43)
    (crate-content crate1 food)
    (crate-content crate2 food)
    (crate-content crate3 food)
    (crate-content crate4 food)
    (crate-content crate5 food)
    (crate-content crate6 food)
    (crate-content crate7 food)
    (crate-content crate8 food)
    (crate-content crate9 food)
    (crate-content crate10 food)
    (crate-content crate11 food)
    (crate-content crate12 food)
    (crate-content crate13 food)
    (crate-content crate14 food)
    (crate-content crate15 food)
    (crate-content crate16 food)
    (crate-content crate17 food)
    (crate-content crate18 food)
    (crate-content crate19 food)
    (crate-content crate20 food)
    (crate-content crate21 food)
    (crate-content crate22 food)
    (crate-content crate23 food)
    (crate-content crate24 medicine)
    (crate-content crate25 medicine)
    (crate-content crate26 medicine)
    (crate-content crate27 medicine)
    (crate-content crate28 medicine)
    (crate-content crate29 medicine)
    (crate-content crate30 medicine)
    (crate-content crate31 medicine)
    (crate-content crate32 medicine)
    (crate-content crate33 medicine)
    (crate-content crate34 medicine)
    (crate-content crate35 medicine)
    (crate-content crate36 medicine)
    (crate-content crate37 medicine)
    (crate-content crate38 medicine)
    (crate-content crate39 medicine)
    (crate-content crate40 medicine)
    (crate-content crate41 medicine)
    (crate-content crate42 medicine)
    (crate-content crate43 medicine)
    (crate-content crate44 medicine)
    (crate-content crate45 medicine)
  )
  (:goal (and
    (has-content person3 food)
    (has-content person3 medicine)
    (has-content person5 food)
    (has-content person5 medicine)
    (has-content person6 medicine)
    (has-content person8 food)
    (has-content person10 food)
    (has-content person12 medicine)
    (has-content person13 medicine)
    (has-content person14 food)
    (has-content person14 medicine)
    (has-content person15 medicine)
    (has-content person16 food)
    (has-content person17 food)
    (has-content person18 food)
    (has-content person18 medicine)
    (has-content person19 medicine)
    (has-content person20 food)
    (has-content person20 medicine)
    (has-content person21 food)
    (has-content person21 medicine)
    (has-content person22 food)
    (has-content person23 food)
    (has-content person23 medicine)
    (has-content person24 food)
    (has-content person24 medicine)
    (has-content person25 food)
    (has-content person25 medicine)
    (has-content person26 food)
    (has-content person26 medicine)
    (has-content person27 food)
    (has-content person28 food)
    (has-content person28 medicine)
    (has-content person30 medicine)
    (has-content person33 food)
    (has-content person36 food)
    (has-content person38 food)
    (has-content person38 medicine)
    (has-content person41 food)
    (has-content person41 medicine)
    (has-content person42 medicine)
    (has-content person43 food)
    (has-content person43 medicine)
    (has-content person44 food)
    (has-content person44 medicine)
  ))
)
