(define (problem problem_d1_r0_l15_p15_c15_g15)
  (:domain emergency-services)
  (:objects
    drone1 - drone
    depot - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    loc10 - location
    loc11 - location
    loc12 - location
    loc13 - location
    loc14 - location
    loc15 - location
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    person10 - person
    person11 - person
    person12 - person
    person13 - person
    person14 - person
    person15 - person
    crate1 - crate
    crate2 - crate
    crate3 - crate
    crate4 - crate
    crate5 - crate
    crate6 - crate
    crate7 - crate
    crate8 - crate
    crate9 - crate
    crate10 - crate
    crate11 - crate
    crate12 - crate
    crate13 - crate
    crate14 - crate
    crate15 - crate
    food - content
    medicine - content
    left - arm
    right - arm
  )
  (:init
    (at-drone drone1 depot)
    (hand-empty drone1 left)
    (hand-empty drone1 right)
    (at-crate crate1 depot)
    (at-crate crate2 depot)
    (at-crate crate3 depot)
    (at-crate crate4 depot)
    (at-crate crate5 depot)
    (at-crate crate6 depot)
    (at-crate crate7 depot)
    (at-crate crate8 depot)
    (at-crate crate9 depot)
    (at-crate crate10 depot)
    (at-crate crate11 depot)
    (at-crate crate12 depot)
    (at-crate crate13 depot)
    (at-crate crate14 depot)
    (at-crate crate15 depot)
    (at-person person1 loc13)
    (at-person person2 loc4)
    (at-person person3 loc12)
    (at-person person4 loc15)
    (at-person person5 loc10)
    (at-person person6 loc4)
    (at-person person7 loc6)
    (at-person person8 loc13)
    (at-person person9 loc1)
    (at-person person10 loc3)
    (at-person person11 loc4)
    (at-person person12 loc5)
    (at-person person13 loc7)
    (at-person person14 loc12)
    (at-person person15 loc9)
    (crate-content crate1 food)
    (crate-content crate2 medicine)
    (crate-content crate3 medicine)
    (crate-content crate4 medicine)
    (crate-content crate5 medicine)
    (crate-content crate6 medicine)
    (crate-content crate7 medicine)
    (crate-content crate8 medicine)
    (crate-content crate9 medicine)
    (crate-content crate10 medicine)
    (crate-content crate11 medicine)
    (crate-content crate12 medicine)
    (crate-content crate13 medicine)
    (crate-content crate14 medicine)
    (crate-content crate15 medicine)
  )
  (:goal (and
    (has-content person1 medicine)
    (has-content person2 medicine)
    (has-content person3 medicine)
    (has-content person4 medicine)
    (has-content person5 medicine)
    (has-content person6 medicine)
    (has-content person7 medicine)
    (has-content person9 medicine)
    (has-content person10 medicine)
    (has-content person11 food)
    (has-content person11 medicine)
    (has-content person12 medicine)
    (has-content person13 medicine)
    (has-content person14 medicine)
    (has-content person15 medicine)
  ))
)
