(define (problem problem_d1_r0_l90_p90_c90_g90)
  (:domain emergency-services)
  (:objects
    drone1 - drone
    depot - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    loc10 - location
    loc11 - location
    loc12 - location
    loc13 - location
    loc14 - location
    loc15 - location
    loc16 - location
    loc17 - location
    loc18 - location
    loc19 - location
    loc20 - location
    loc21 - location
    loc22 - location
    loc23 - location
    loc24 - location
    loc25 - location
    loc26 - location
    loc27 - location
    loc28 - location
    loc29 - location
    loc30 - location
    loc31 - location
    loc32 - location
    loc33 - location
    loc34 - location
    loc35 - location
    loc36 - location
    loc37 - location
    loc38 - location
    loc39 - location
    loc40 - location
    loc41 - location
    loc42 - location
    loc43 - location
    loc44 - location
    loc45 - location
    loc46 - location
    loc47 - location
    loc48 - location
    loc49 - location
    loc50 - location
    loc51 - location
    loc52 - location
    loc53 - location
    loc54 - location
    loc55 - location
    loc56 - location
    loc57 - location
    loc58 - location
    loc59 - location
    loc60 - location
    loc61 - location
    loc62 - location
    loc63 - location
    loc64 - location
    loc65 - location
    loc66 - location
    loc67 - location
    loc68 - location
    loc69 - location
    loc70 - location
    loc71 - location
    loc72 - location
    loc73 - location
    loc74 - location
    loc75 - location
    loc76 - location
    loc77 - location
    loc78 - location
    loc79 - location
    loc80 - location
    loc81 - location
    loc82 - location
    loc83 - location
    loc84 - location
    loc85 - location
    loc86 - location
    loc87 - location
    loc88 - location
    loc89 - location
    loc90 - location
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    person10 - person
    person11 - person
    person12 - person
    person13 - person
    person14 - person
    person15 - person
    person16 - person
    person17 - person
    person18 - person
    person19 - person
    person20 - person
    person21 - person
    person22 - person
    person23 - person
    person24 - person
    person25 - person
    person26 - person
    person27 - person
    person28 - person
    person29 - person
    person30 - person
    person31 - person
    person32 - person
    person33 - person
    person34 - person
    person35 - person
    person36 - person
    person37 - person
    person38 - person
    person39 - person
    person40 - person
    person41 - person
    person42 - person
    person43 - person
    person44 - person
    person45 - person
    person46 - person
    person47 - person
    person48 - person
    person49 - person
    person50 - person
    person51 - person
    person52 - person
    person53 - person
    person54 - person
    person55 - person
    person56 - person
    person57 - person
    person58 - person
    person59 - person
    person60 - person
    person61 - person
    person62 - person
    person63 - person
    person64 - person
    person65 - person
    person66 - person
    person67 - person
    person68 - person
    person69 - person
    person70 - person
    person71 - person
    person72 - person
    person73 - person
    person74 - person
    person75 - person
    person76 - person
    person77 - person
    person78 - person
    person79 - person
    person80 - person
    person81 - person
    person82 - person
    person83 - person
    person84 - person
    person85 - person
    person86 - person
    person87 - person
    person88 - person
    person89 - person
    person90 - person
    crate1 - crate
    crate2 - crate
    crate3 - crate
    crate4 - crate
    crate5 - crate
    crate6 - crate
    crate7 - crate
    crate8 - crate
    crate9 - crate
    crate10 - crate
    crate11 - crate
    crate12 - crate
    crate13 - crate
    crate14 - crate
    crate15 - crate
    crate16 - crate
    crate17 - crate
    crate18 - crate
    crate19 - crate
    crate20 - crate
    crate21 - crate
    crate22 - crate
    crate23 - crate
    crate24 - crate
    crate25 - crate
    crate26 - crate
    crate27 - crate
    crate28 - crate
    crate29 - crate
    crate30 - crate
    crate31 - crate
    crate32 - crate
    crate33 - crate
    crate34 - crate
    crate35 - crate
    crate36 - crate
    crate37 - crate
    crate38 - crate
    crate39 - crate
    crate40 - crate
    crate41 - crate
    crate42 - crate
    crate43 - crate
    crate44 - crate
    crate45 - crate
    crate46 - crate
    crate47 - crate
    crate48 - crate
    crate49 - crate
    crate50 - crate
    crate51 - crate
    crate52 - crate
    crate53 - crate
    crate54 - crate
    crate55 - crate
    crate56 - crate
    crate57 - crate
    crate58 - crate
    crate59 - crate
    crate60 - crate
    crate61 - crate
    crate62 - crate
    crate63 - crate
    crate64 - crate
    crate65 - crate
    crate66 - crate
    crate67 - crate
    crate68 - crate
    crate69 - crate
    crate70 - crate
    crate71 - crate
    crate72 - crate
    crate73 - crate
    crate74 - crate
    crate75 - crate
    crate76 - crate
    crate77 - crate
    crate78 - crate
    crate79 - crate
    crate80 - crate
    crate81 - crate
    crate82 - crate
    crate83 - crate
    crate84 - crate
    crate85 - crate
    crate86 - crate
    crate87 - crate
    crate88 - crate
    crate89 - crate
    crate90 - crate
    food - content
    medicine - content
    left - arm
    right - arm
  )
  (:init
    (at-drone drone1 depot)
    (hand-empty drone1 left)
    (hand-empty drone1 right)
    (at-crate crate1 depot)
    (at-crate crate2 depot)
    (at-crate crate3 depot)
    (at-crate crate4 depot)
    (at-crate crate5 depot)
    (at-crate crate6 depot)
    (at-crate crate7 depot)
    (at-crate crate8 depot)
    (at-crate crate9 depot)
    (at-crate crate10 depot)
    (at-crate crate11 depot)
    (at-crate crate12 depot)
    (at-crate crate13 depot)
    (at-crate crate14 depot)
    (at-crate crate15 depot)
    (at-crate crate16 depot)
    (at-crate crate17 depot)
    (at-crate crate18 depot)
    (at-crate crate19 depot)
    (at-crate crate20 depot)
    (at-crate crate21 depot)
    (at-crate crate22 depot)
    (at-crate crate23 depot)
    (at-crate crate24 depot)
    (at-crate crate25 depot)
    (at-crate crate26 depot)
    (at-crate crate27 depot)
    (at-crate crate28 depot)
    (at-crate crate29 depot)
    (at-crate crate30 depot)
    (at-crate crate31 depot)
    (at-crate crate32 depot)
    (at-crate crate33 depot)
    (at-crate crate34 depot)
    (at-crate crate35 depot)
    (at-crate crate36 depot)
    (at-crate crate37 depot)
    (at-crate crate38 depot)
    (at-crate crate39 depot)
    (at-crate crate40 depot)
    (at-crate crate41 depot)
    (at-crate crate42 depot)
    (at-crate crate43 depot)
    (at-crate crate44 depot)
    (at-crate crate45 depot)
    (at-crate crate46 depot)
    (at-crate crate47 depot)
    (at-crate crate48 depot)
    (at-crate crate49 depot)
    (at-crate crate50 depot)
    (at-crate crate51 depot)
    (at-crate crate52 depot)
    (at-crate crate53 depot)
    (at-crate crate54 depot)
    (at-crate crate55 depot)
    (at-crate crate56 depot)
    (at-crate crate57 depot)
    (at-crate crate58 depot)
    (at-crate crate59 depot)
    (at-crate crate60 depot)
    (at-crate crate61 depot)
    (at-crate crate62 depot)
    (at-crate crate63 depot)
    (at-crate crate64 depot)
    (at-crate crate65 depot)
    (at-crate crate66 depot)
    (at-crate crate67 depot)
    (at-crate crate68 depot)
    (at-crate crate69 depot)
    (at-crate crate70 depot)
    (at-crate crate71 depot)
    (at-crate crate72 depot)
    (at-crate crate73 depot)
    (at-crate crate74 depot)
    (at-crate crate75 depot)
    (at-crate crate76 depot)
    (at-crate crate77 depot)
    (at-crate crate78 depot)
    (at-crate crate79 depot)
    (at-crate crate80 depot)
    (at-crate crate81 depot)
    (at-crate crate82 depot)
    (at-crate crate83 depot)
    (at-crate crate84 depot)
    (at-crate crate85 depot)
    (at-crate crate86 depot)
    (at-crate crate87 depot)
    (at-crate crate88 depot)
    (at-crate crate89 depot)
    (at-crate crate90 depot)
    (at-person person1 loc14)
    (at-person person2 loc54)
    (at-person person3 loc31)
    (at-person person4 loc17)
    (at-person person5 loc74)
    (at-person person6 loc89)
    (at-person person7 loc80)
    (at-person person8 loc90)
    (at-person person9 loc79)
    (at-person person10 loc69)
    (at-person person11 loc38)
    (at-person person12 loc73)
    (at-person person13 loc20)
    (at-person person14 loc28)
    (at-person person15 loc67)
    (at-person person16 loc38)
    (at-person person17 loc35)
    (at-person person18 loc32)
    (at-person person19 loc77)
    (at-person person20 loc84)
    (at-person person21 loc66)
    (at-person person22 loc29)
    (at-person person23 loc79)
    (at-person person24 loc3)
    (at-person person25 loc67)
    (at-person person26 loc80)
    (at-person person27 loc89)
    (at-person person28 loc22)
    (at-person person29 loc23)
    (at-person person30 loc90)
    (at-person person31 loc5)
    (at-person person32 loc76)
    (at-person person33 loc71)
    (at-person person34 loc12)
    (at-person person35 loc26)
    (at-person person36 loc64)
    (at-person person37 loc5)
    (at-person person38 loc54)
    (at-person person39 loc63)
    (at-person person40 loc4)
    (at-person person41 loc25)
    (at-person person42 loc2)
    (at-person person43 loc32)
    (at-person person44 loc49)
    (at-person person45 loc87)
    (at-person person46 loc71)
    (at-person person47 loc13)
    (at-person person48 loc54)
    (at-person person49 loc24)
    (at-person person50 loc16)
    (at-person person51 loc70)
    (at-person person52 loc67)
    (at-person person53 loc47)
    (at-person person54 loc77)
    (at-person person55 loc77)
    (at-person person56 loc61)
    (at-person person57 loc26)
    (at-person person58 loc1)
    (at-person person59 loc55)
    (at-person person60 loc45)
    (at-person person61 loc17)
    (at-person person62 loc39)
    (at-person person63 loc90)
    (at-person person64 loc77)
    (at-person person65 loc88)
    (at-person person66 loc90)
    (at-person person67 loc27)
    (at-person person68 loc75)
    (at-person person69 loc26)
    (at-person person70 loc69)
    (at-person person71 loc44)
    (at-person person72 loc48)
    (at-person person73 loc23)
    (at-person person74 loc15)
    (at-person person75 loc20)
    (at-person person76 loc2)
    (at-person person77 loc79)
    (at-person person78 loc49)
    (at-person person79 loc76)
    (at-person person80 loc35)
    (at-person person81 loc55)
    (at-person person82 loc90)
    (at-person person83 loc51)
    (at-person person84 loc45)
    (at-person person85 loc8)
    (at-person person86 loc79)
    (at-person person87 loc67)
    (at-person person88 loc59)
    (at-person person89 loc44)
    (at-person person90 loc1)
    (crate-content crate1 food)
    (crate-content crate2 food)
    (crate-content crate3 food)
    (crate-content crate4 food)
    (crate-content crate5 food)
    (crate-content crate6 food)
    (crate-content crate7 food)
    (crate-content crate8 food)
    (crate-content crate9 food)
    (crate-content crate10 food)
    (crate-content crate11 food)
    (crate-content crate12 food)
    (crate-content crate13 food)
    (crate-content crate14 food)
    (crate-content crate15 food)
    (crate-content crate16 food)
    (crate-content crate17 food)
    (crate-content crate18 food)
    (crate-content crate19 food)
    (crate-content crate20 food)
    (crate-content crate21 food)
    (crate-content crate22 food)
    (crate-content crate23 food)
    (crate-content crate24 food)
    (crate-content crate25 food)
    (crate-content crate26 food)
    (crate-content crate27 food)
    (crate-content crate28 food)
    (crate-content crate29 food)
    (crate-content crate30 food)
    (crate-content crate31 food)
    (crate-content crate32 food)
    (crate-content crate33 food)
    (crate-content crate34 food)
    (crate-content crate35 food)
    (crate-content crate36 food)
    (crate-content crate37 food)
    (crate-content crate38 food)
    (crate-content crate39 food)
    (crate-content crate40 food)
    (crate-content crate41 food)
    (crate-content crate42 food)
    (crate-content crate43 food)
    (crate-content crate44 food)
    (crate-content crate45 food)
    (crate-content crate46 food)
    (crate-content crate47 food)
    (crate-content crate48 food)
    (crate-content crate49 food)
    (crate-content crate50 food)
    (crate-content crate51 food)
    (crate-content crate52 food)
    (crate-content crate53 food)
    (crate-content crate54 food)
    (crate-content crate55 food)
    (crate-content crate56 food)
    (crate-content crate57 food)
    (crate-content crate58 food)
    (crate-content crate59 food)
    (crate-content crate60 food)
    (crate-content crate61 food)
    (crate-content crate62 food)
    (crate-content crate63 food)
    (crate-content crate64 food)
    (crate-content crate65 food)
    (crate-content crate66 food)
    (crate-content crate67 food)
    (crate-content crate68 food)
    (crate-content crate69 food)
    (crate-content crate70 food)
    (crate-content crate71 food)
    (crate-content crate72 food)
    (crate-content crate73 food)
    (crate-content crate74 food)
    (crate-content crate75 food)
    (crate-content crate76 food)
    (crate-content crate77 food)
    (crate-content crate78 food)
    (crate-content crate79 food)
    (crate-content crate80 food)
    (crate-content crate81 food)
    (crate-content crate82 food)
    (crate-content crate83 food)
    (crate-content crate84 food)
    (crate-content crate85 food)
    (crate-content crate86 food)
    (crate-content crate87 medicine)
    (crate-content crate88 medicine)
    (crate-content crate89 medicine)
    (crate-content crate90 medicine)
  )
  (:goal (and
    (has-content person1 food)
    (has-content person2 food)
    (has-content person3 food)
    (has-content person5 food)
    (has-content person6 food)
    (has-content person7 food)
    (has-content person8 food)
    (has-content person9 food)
    (has-content person11 food)
    (has-content person11 medicine)
    (has-content person12 food)
    (has-content person13 food)
    (has-content person14 food)
    (has-content person15 food)
    (has-content person16 food)
    (has-content person17 food)
    (has-content person18 food)
    (has-content person19 food)
    (has-content person20 food)
    (has-content person21 food)
    (has-content person22 food)
    (has-content person23 food)
    (has-content person24 food)
    (has-content person25 food)
    (has-content person26 food)
    (has-content person27 food)
    (has-content person28 food)
    (has-content person29 food)
    (has-content person30 food)
    (has-content person31 food)
    (has-content person32 food)
    (has-content person33 food)
    (has-content person34 food)
    (has-content person35 food)
    (has-content person36 food)
    (has-content person37 food)
    (has-content person38 food)
    (has-content person39 food)
    (has-content person40 food)
    (has-content person42 food)
    (has-content person43 food)
    (has-content person44 food)
    (has-content person45 food)
    (has-content person46 food)
    (has-content person47 food)
    (has-content person48 food)
    (has-content person49 food)
    (has-content person50 food)
    (has-content person51 food)
    (has-content person52 food)
    (has-content person53 food)
    (has-content person54 food)
    (has-content person55 food)
    (has-content person56 food)
    (has-content person57 food)
    (has-content person58 food)
    (has-content person59 food)
    (has-content person60 food)
    (has-content person61 food)
    (has-content person62 food)
    (has-content person63 food)
    (has-content person64 food)
    (has-content person65 food)
    (has-content person66 food)
    (has-content person67 food)
    (has-content person68 food)
    (has-content person69 food)
    (has-content person70 food)
    (has-content person70 medicine)
    (has-content person72 food)
    (has-content person73 food)
    (has-content person73 medicine)
    (has-content person74 food)
    (has-content person75 food)
    (has-content person76 food)
    (has-content person77 food)
    (has-content person78 food)
    (has-content person79 food)
    (has-content person80 food)
    (has-content person81 food)
    (has-content person82 food)
    (has-content person83 food)
    (has-content person84 food)
    (has-content person85 food)
    (has-content person86 food)
    (has-content person87 food)
    (has-content person88 food)
    (has-content person89 food)
    (has-content person89 medicine)
    (has-content person90 food)
  ))
)
