(define (problem problem_d1_r0_l20_p20_c20_g20)
  (:domain emergency-services)
  (:objects
    drone1 - drone
    depot - location
    loc1 - location
    loc2 - location
    loc3 - location
    loc4 - location
    loc5 - location
    loc6 - location
    loc7 - location
    loc8 - location
    loc9 - location
    loc10 - location
    loc11 - location
    loc12 - location
    loc13 - location
    loc14 - location
    loc15 - location
    loc16 - location
    loc17 - location
    loc18 - location
    loc19 - location
    loc20 - location
    person1 - person
    person2 - person
    person3 - person
    person4 - person
    person5 - person
    person6 - person
    person7 - person
    person8 - person
    person9 - person
    person10 - person
    person11 - person
    person12 - person
    person13 - person
    person14 - person
    person15 - person
    person16 - person
    person17 - person
    person18 - person
    person19 - person
    person20 - person
    crate1 - crate
    crate2 - crate
    crate3 - crate
    crate4 - crate
    crate5 - crate
    crate6 - crate
    crate7 - crate
    crate8 - crate
    crate9 - crate
    crate10 - crate
    crate11 - crate
    crate12 - crate
    crate13 - crate
    crate14 - crate
    crate15 - crate
    crate16 - crate
    crate17 - crate
    crate18 - crate
    crate19 - crate
    crate20 - crate
    food - content
    medicine - content
    left - arm
    right - arm
  )
  (:init
    (at-drone drone1 depot)
    (hand-empty drone1 left)
    (hand-empty drone1 right)
    (at-crate crate1 depot)
    (at-crate crate2 depot)
    (at-crate crate3 depot)
    (at-crate crate4 depot)
    (at-crate crate5 depot)
    (at-crate crate6 depot)
    (at-crate crate7 depot)
    (at-crate crate8 depot)
    (at-crate crate9 depot)
    (at-crate crate10 depot)
    (at-crate crate11 depot)
    (at-crate crate12 depot)
    (at-crate crate13 depot)
    (at-crate crate14 depot)
    (at-crate crate15 depot)
    (at-crate crate16 depot)
    (at-crate crate17 depot)
    (at-crate crate18 depot)
    (at-crate crate19 depot)
    (at-crate crate20 depot)
    (at-person person1 loc19)
    (at-person person2 loc11)
    (at-person person3 loc16)
    (at-person person4 loc13)
    (at-person person5 loc1)
    (at-person person6 loc18)
    (at-person person7 loc18)
    (at-person person8 loc3)
    (at-person person9 loc17)
    (at-person person10 loc3)
    (at-person person11 loc11)
    (at-person person12 loc11)
    (at-person person13 loc4)
    (at-person person14 loc5)
    (at-person person15 loc17)
    (at-person person16 loc11)
    (at-person person17 loc5)
    (at-person person18 loc5)
    (at-person person19 loc2)
    (at-person person20 loc11)
    (crate-content crate1 food)
    (crate-content crate2 food)
    (crate-content crate3 food)
    (crate-content crate4 food)
    (crate-content crate5 food)
    (crate-content crate6 food)
    (crate-content crate7 food)
    (crate-content crate8 food)
    (crate-content crate9 food)
    (crate-content crate10 food)
    (crate-content crate11 food)
    (crate-content crate12 food)
    (crate-content crate13 food)
    (crate-content crate14 food)
    (crate-content crate15 food)
    (crate-content crate16 medicine)
    (crate-content crate17 medicine)
    (crate-content crate18 medicine)
    (crate-content crate19 medicine)
    (crate-content crate20 medicine)
  )
  (:goal (and
    (has-content person1 food)
    (has-content person2 food)
    (has-content person2 medicine)
    (has-content person3 food)
    (has-content person5 food)
    (has-content person6 food)
    (has-content person7 food)
    (has-content person7 medicine)
    (has-content person9 food)
    (has-content person10 food)
    (has-content person12 food)
    (has-content person13 food)
    (has-content person15 food)
    (has-content person16 food)
    (has-content person16 medicine)
    (has-content person17 food)
    (has-content person17 medicine)
    (has-content person18 food)
    (has-content person18 medicine)
    (has-content person20 food)
  ))
)
